FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

COPY package.json package-lock.json /app/

COPY frontend/package.json /app/frontend/

RUN npm ci

COPY ./frontend /app/frontend
WORKDIR /app/frontend

ARG VITE_API_URL

CMD ["npm", "test"]
