// This file is auto-generated by @hey-api/openapi-ts

export const AssetKindSchema = {
    type: 'string',
    enum: ['mold', 'part', 'scan', 'drawing', 'moldflow'],
    title: 'AssetKind'
} as const;

export const Body_files_upload_fileSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_files-upload_file'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CadCameraSchema = {
    properties: {
        position: {
            prefixItems: [
                {
                    type: 'number'
                },
                {
                    type: 'number'
                },
                {
                    type: 'number'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Position'
        },
        target: {
            prefixItems: [
                {
                    type: 'number'
                },
                {
                    type: 'number'
                },
                {
                    type: 'number'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Target'
        },
        up: {
            prefixItems: [
                {
                    type: 'number'
                },
                {
                    type: 'number'
                },
                {
                    type: 'number'
                }
            ],
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Up'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['position', 'target', 'up'],
    title: 'CadCamera'
} as const;

export const CadFaceSelectionSchema = {
    properties: {
        mesh: {
            type: 'integer',
            maximum: 1000000,
            minimum: 0,
            title: 'Mesh'
        },
        face: {
            type: 'integer',
            maximum: 1000000,
            minimum: 0,
            title: 'Face'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['mesh', 'face'],
    title: 'CadFaceSelection'
} as const;

export const CharacteristicAssignmentSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            pattern: '^N\\d{1,6}(?:\\.\\d{1,3})?$',
            title: 'Code'
        },
        revision: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Revision'
        },
        role: {
            type: 'string',
            enum: ['primary', 'reference', 'context'],
            title: 'Role',
            default: 'primary'
        }
    },
    type: 'object',
    required: ['code', 'revision'],
    title: 'CharacteristicAssignment'
} as const;

export const CharacteristicPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        part_id: {
            type: 'string',
            format: 'uuid',
            title: 'Part Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        revision: {
            type: 'string',
            title: 'Revision'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        }
    },
    type: 'object',
    required: ['id', 'part_id', 'code', 'revision', 'title'],
    title: 'CharacteristicPublic'
} as const;

export const DrawingPublicSchema = {
    properties: {
        state: {
            type: 'string',
            title: 'State'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload',
            default: {}
        },
        reviews: {
            items: {
                '$ref': '#/components/schemas/LocationPublic'
            },
            type: 'array',
            title: 'Reviews',
            default: []
        }
    },
    type: 'object',
    required: ['state'],
    title: 'DrawingPublic'
} as const;

export const EvidenceDocumentSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        content_type: {
            type: 'string',
            title: 'Content Type'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        source: {
            type: 'string',
            title: 'Source',
            default: 'upload'
        },
        version: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        revision: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revision'
        },
        relative_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relative Path'
        }
    },
    type: 'object',
    required: ['id', 'filename', 'content_type', 'size'],
    title: 'EvidenceDocument'
} as const;

export const FeatureAssetCreateSchema = {
    properties: {
        kind: {
            '$ref': '#/components/schemas/AssetKind'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        },
        part_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Part Id'
        },
        file_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Id'
        }
    },
    type: 'object',
    required: ['kind', 'name'],
    title: 'FeatureAssetCreate'
} as const;

export const FeatureAssetOrderSchema = {
    properties: {
        part_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Part Id'
        },
        asset_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Asset Ids'
        }
    },
    type: 'object',
    required: ['asset_ids'],
    title: 'FeatureAssetOrder'
} as const;

export const FeatureAssetPublicSchema = {
    properties: {
        kind: {
            '$ref': '#/components/schemas/AssetKind'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        feature_id: {
            type: 'string',
            format: 'uuid',
            title: 'Feature Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        part: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PartPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        file: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FilePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['kind', 'name', 'id', 'feature_id'],
    title: 'FeatureAssetPublic'
} as const;

export const FeatureAssetUpdateSchema = {
    properties: {
        kind: {
            '$ref': '#/components/schemas/AssetKind'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        part_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Part Id'
        },
        file_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Id'
        }
    },
    type: 'object',
    title: 'FeatureAssetUpdate'
} as const;

export const FeatureCategorySchema = {
    type: 'string',
    enum: ['hole', 'rib', 'thickness', 'boss', 'fillet', 'draft', 'other'],
    title: 'FeatureCategory'
} as const;

export const FeatureCover3DSchema = {
    properties: {
        asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Asset Id'
        },
        part_id: {
            type: 'string',
            format: 'uuid',
            title: 'Part Id'
        },
        file_id: {
            type: 'string',
            format: 'uuid',
            title: 'File Id'
        },
        file_version: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Version'
        },
        source_sha256: {
            type: 'string',
            pattern: '^[0-9a-f]{64}$',
            title: 'Source Sha256'
        },
        geometry_key: {
            type: 'string',
            pattern: '^[0-9a-f]{64}$',
            title: 'Geometry Key'
        },
        recipe: {
            type: 'string',
            const: 'occt-import-js@0.0.23/cover-v1',
            title: 'Recipe'
        },
        faces: {
            items: {
                '$ref': '#/components/schemas/CadFaceSelection'
            },
            type: 'array',
            maxItems: 5000,
            minItems: 1,
            title: 'Faces'
        },
        camera: {
            '$ref': '#/components/schemas/CadCamera'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['asset_id', 'part_id', 'file_id', 'source_sha256', 'geometry_key', 'recipe', 'faces', 'camera'],
    title: 'FeatureCover3D',
    description: 'An annotation tied to exact source bytes and a deterministic tessellation.'
} as const;

export const FeatureCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        image_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Id'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'FeatureCreate'
} as const;

export const FeatureDetailSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        },
        image: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FilePublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        cover_3d: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCover3D'
                },
                {
                    type: 'null'
                }
            ]
        },
        part_order: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Part Order'
        },
        assets: {
            items: {
                '$ref': '#/components/schemas/FeatureAssetPublic'
            },
            type: 'array',
            title: 'Assets',
            default: []
        },
        parts: {
            items: {
                '$ref': '#/components/schemas/PartPublic'
            },
            type: 'array',
            title: 'Parts',
            default: []
        },
        notes: {
            items: {
                '$ref': '#/components/schemas/FeatureNotePublic'
            },
            type: 'array',
            title: 'Notes',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'FeatureDetail'
} as const;

export const FeatureEvidencePublicSchema = {
    properties: {
        characteristics: {
            items: {
                '$ref': '#/components/schemas/CharacteristicPublic'
            },
            type: 'array',
            title: 'Characteristics'
        },
        pending: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Pending'
        },
        cases: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Cases'
        }
    },
    type: 'object',
    required: ['characteristics', 'pending', 'cases'],
    title: 'FeatureEvidencePublic'
} as const;

export const FeatureFilterOptionSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        part_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Part Ids'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'FeatureFilterOption'
} as const;

export const FeatureFiltersSchema = {
    properties: {
        categories: {
            items: {
                '$ref': '#/components/schemas/FeatureCategory'
            },
            type: 'array',
            title: 'Categories'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        parts: {
            items: {
                '$ref': '#/components/schemas/PartPublic'
            },
            type: 'array',
            title: 'Parts'
        },
        features: {
            items: {
                '$ref': '#/components/schemas/FeatureFilterOption'
            },
            type: 'array',
            title: 'Features'
        }
    },
    type: 'object',
    required: ['categories', 'tags', 'parts', 'features'],
    title: 'FeatureFilters'
} as const;

export const FeatureNoteCreateSchema = {
    properties: {
        kind: {
            '$ref': '#/components/schemas/NoteKind'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        body: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        }
    },
    type: 'object',
    required: ['kind', 'title'],
    title: 'FeatureNoteCreate'
} as const;

export const FeatureNoteOrderSchema = {
    properties: {
        kind: {
            '$ref': '#/components/schemas/NoteKind'
        },
        note_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Note Ids'
        }
    },
    type: 'object',
    required: ['kind', 'note_ids'],
    title: 'FeatureNoteOrder'
} as const;

export const FeatureNotePublicSchema = {
    properties: {
        kind: {
            '$ref': '#/components/schemas/NoteKind'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        body: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        feature_id: {
            type: 'string',
            format: 'uuid',
            title: 'Feature Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['kind', 'title', 'id', 'feature_id'],
    title: 'FeatureNotePublic'
} as const;

export const FeatureNoteUpdateSchema = {
    properties: {
        kind: {
            '$ref': '#/components/schemas/NoteKind'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        body: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        position: {
            type: 'integer',
            title: 'Position'
        }
    },
    type: 'object',
    title: 'FeatureNoteUpdate'
} as const;

export const FeaturePartOrderSchema = {
    properties: {
        part_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Part Ids'
        }
    },
    type: 'object',
    required: ['part_ids'],
    title: 'FeaturePartOrder'
} as const;

export const FeaturePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        },
        image: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FilePublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        cover_3d: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCover3D'
                },
                {
                    type: 'null'
                }
            ]
        },
        part_order: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Part Order'
        },
        assets: {
            items: {
                '$ref': '#/components/schemas/FeatureAssetPublic'
            },
            type: 'array',
            title: 'Assets',
            default: []
        },
        parts: {
            items: {
                '$ref': '#/components/schemas/PartPublic'
            },
            type: 'array',
            title: 'Parts',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'FeaturePublic'
} as const;

export const FeatureUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        image_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Id'
        },
        cover_3d: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCover3D'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'FeatureUpdate'
} as const;

export const FeaturesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FeaturePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FeaturesPublic'
} as const;

export const FileAccessPublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['url', 'expires_at'],
    title: 'FileAccessPublic'
} as const;

export const FilePreviewPublicSchema = {
    properties: {
        state: {
            type: 'string',
            enum: ['queued', 'processing', 'ready', 'error'],
            title: 'State'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        }
    },
    type: 'object',
    required: ['state'],
    title: 'FilePreviewPublic'
} as const;

export const FilePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        content_type: {
            type: 'string',
            title: 'Content Type'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        source: {
            type: 'string',
            title: 'Source',
            default: 'upload'
        },
        version: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        revision: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revision'
        }
    },
    type: 'object',
    required: ['id', 'filename', 'content_type', 'size'],
    title: 'FilePublic'
} as const;

export const FileStatusSchema = {
    properties: {
        state: {
            type: 'string',
            enum: ['available', 'missing', 'changed', 'unavailable'],
            title: 'State'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        }
    },
    type: 'object',
    required: ['state', 'message'],
    title: 'FileStatus'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const JobPublicSchema = {
    properties: {
        state: {
            type: 'string',
            title: 'State'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload',
            default: {}
        }
    },
    type: 'object',
    required: ['state'],
    title: 'JobPublic'
} as const;

export const LocalFileReferenceSchema = {
    properties: {
        path: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Path'
        },
        revision: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revision'
        }
    },
    type: 'object',
    required: ['path'],
    title: 'LocalFileReference'
} as const;

export const LocationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        candidate_id: {
            type: 'string',
            title: 'Candidate Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        box: {
            items: {
                type: 'number'
            },
            type: 'array',
            title: 'Box'
        },
        reviewed_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed By'
        },
        reviewed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Reviewed At'
        }
    },
    type: 'object',
    required: ['id', 'candidate_id', 'label', 'page', 'box', 'reviewed_by', 'reviewed_at'],
    title: 'LocationPublic'
} as const;

export const LocationReviewSchema = {
    properties: {
        sha256: {
            type: 'string',
            pattern: '^[0-9a-f]{64}$',
            title: 'Sha256'
        },
        candidate_id: {
            type: 'string',
            maxLength: 96,
            minLength: 1,
            title: 'Candidate Id'
        },
        label: {
            type: 'string',
            maxLength: 64,
            pattern: '^N\\d{1,6}(?:\\.\\d{1,3})?$',
            title: 'Label'
        }
    },
    type: 'object',
    required: ['sha256', 'candidate_id', 'label'],
    title: 'LocationReview'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MetrologyCatalogSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MetrologyPart'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        features: {
            items: {
                '$ref': '#/components/schemas/MetrologyFeature'
            },
            type: 'array',
            title: 'Features'
        }
    },
    type: 'object',
    required: ['data', 'count', 'features'],
    title: 'MetrologyCatalog'
} as const;

export const MetrologyFeatureSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        characteristics: {
            items: {
                '$ref': '#/components/schemas/CharacteristicPublic'
            },
            type: 'array',
            title: 'Characteristics',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'MetrologyFeature'
} as const;

export const MetrologyFeatureChoiceSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FeatureCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        part_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Part Ids',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'MetrologyFeatureChoice'
} as const;

export const MetrologyFiltersSchema = {
    properties: {
        parts: {
            items: {
                '$ref': '#/components/schemas/PartPublic'
            },
            type: 'array',
            title: 'Parts'
        },
        features: {
            items: {
                '$ref': '#/components/schemas/MetrologyFeatureChoice'
            },
            type: 'array',
            title: 'Features'
        }
    },
    type: 'object',
    required: ['parts', 'features'],
    title: 'MetrologyFilters'
} as const;

export const MetrologyPartSchema = {
    properties: {
        part: {
            '$ref': '#/components/schemas/PartPublic'
        },
        features: {
            items: {
                '$ref': '#/components/schemas/MetrologyFeature'
            },
            type: 'array',
            title: 'Features'
        },
        matched_feature_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Matched Feature Ids',
            default: []
        }
    },
    type: 'object',
    required: ['part', 'features'],
    title: 'MetrologyPart'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NoteKindSchema = {
    type: 'string',
    enum: ['warning', 'lesson'],
    title: 'NoteKind'
} as const;

export const PartCatalogPublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        folder_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Folder Path'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        feature_count: {
            type: 'integer',
            title: 'Feature Count'
        }
    },
    type: 'object',
    required: ['code', 'id', 'feature_count'],
    title: 'PartCatalogPublic'
} as const;

export const PartCreateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        folder_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Folder Path'
        }
    },
    type: 'object',
    required: ['code'],
    title: 'PartCreate'
} as const;

export const PartEvidencePublicSchema = {
    properties: {
        part: {
            '$ref': '#/components/schemas/PartPublic'
        },
        documents: {
            items: {
                '$ref': '#/components/schemas/EvidenceDocument'
            },
            type: 'array',
            title: 'Documents'
        },
        characteristics: {
            items: {
                '$ref': '#/components/schemas/CharacteristicPublic'
            },
            type: 'array',
            title: 'Characteristics'
        },
        features: {
            items: {
                '$ref': '#/components/schemas/MetrologyFeature'
            },
            type: 'array',
            title: 'Features',
            default: []
        },
        study: {
            '$ref': '#/components/schemas/JobPublic'
        },
        import_available: {
            type: 'boolean',
            title: 'Import Available'
        }
    },
    type: 'object',
    required: ['part', 'documents', 'characteristics', 'study', 'import_available'],
    title: 'PartEvidencePublic'
} as const;

export const PartFromFolderSchema = {
    properties: {
        folder_path: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Folder Path'
        }
    },
    type: 'object',
    required: ['folder_path'],
    title: 'PartFromFolder'
} as const;

export const PartPublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        folder_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Folder Path'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['code', 'id'],
    title: 'PartPublic'
} as const;

export const PartUpdateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        folder_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Folder Path'
        }
    },
    type: 'object',
    title: 'PartUpdate'
} as const;

export const PartsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PartCatalogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PartsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RelinkFileReferenceSchema = {
    properties: {
        path: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Path'
        },
        revision: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revision'
        },
        expected_version: {
            type: 'string',
            format: 'uuid',
            title: 'Expected Version'
        }
    },
    type: 'object',
    required: ['path', 'expected_version'],
    title: 'RelinkFileReference'
} as const;

export const SourceEntrySchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        directory: {
            type: 'boolean',
            title: 'Directory'
        },
        size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        }
    },
    type: 'object',
    required: ['name', 'path', 'directory'],
    title: 'SourceEntry'
} as const;

export const SourceListingSchema = {
    properties: {
        configured: {
            type: 'boolean',
            title: 'Configured'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        entries: {
            items: {
                '$ref': '#/components/schemas/SourceEntry'
            },
            type: 'array',
            title: 'Entries'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['configured', 'name', 'path', 'entries', 'count'],
    title: 'SourceListing'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;