// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { FeaturesReadFeaturesData, FeaturesReadFeaturesResponse, FeaturesCreateFeatureData, FeaturesCreateFeatureResponse, FeaturesReadFeatureFiltersResponse, FeaturesReadFeatureData, FeaturesReadFeatureResponse, FeaturesUpdateFeatureData, FeaturesUpdateFeatureResponse, FeaturesDeleteFeatureData, FeaturesDeleteFeatureResponse, FeaturesCreateFeatureNoteData, FeaturesCreateFeatureNoteResponse, FeaturesUpdateFeatureNoteData, FeaturesUpdateFeatureNoteResponse, FeaturesDeleteFeatureNoteData, FeaturesDeleteFeatureNoteResponse, FeaturesCreateFeatureAssetData, FeaturesCreateFeatureAssetResponse, FeaturesUpdateFeatureAssetData, FeaturesUpdateFeatureAssetResponse, FeaturesDeleteFeatureAssetData, FeaturesDeleteFeatureAssetResponse, FilesUploadFileData, FilesUploadFileResponse, FilesReadFileData, FilesReadFileResponse, FilesDeleteFileData, FilesDeleteFileResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class FeaturesService {
    /**
     * Read Features
     * Buscar features.
     *
     * `q` busca a la vez en nombre, descripcion, tags, nombres y codigos de las
     * piezas ejemplo, y texto de warnings y lessons learned. `category`, `tag` y
     * `mold` son los filtros adicionales del dashboard.
     * @param data The data for the request.
     * @param data.q
     * @param data.category
     * @param data.tag
     * @param data.mold
     * @param data.skip
     * @param data.limit
     * @returns FeaturesPublic Successful Response
     * @throws ApiError
     */
    public static readFeatures(data: FeaturesReadFeaturesData = {}): CancelablePromise<FeaturesReadFeaturesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/features/',
            query: {
                q: data.q,
                category: data.category,
                tag: data.tag,
                mold: data.mold,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Feature
     * Crear un feature.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns FeaturePublic Successful Response
     * @throws ApiError
     */
    public static createFeature(data: FeaturesCreateFeatureData): CancelablePromise<FeaturesCreateFeatureResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/features/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Feature Filters
     * Valores disponibles para los desplegables de filtrado del dashboard.
     * @returns FeatureFilters Successful Response
     * @throws ApiError
     */
    public static readFeatureFilters(): CancelablePromise<FeaturesReadFeatureFiltersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/features/filters'
        });
    }
    
    /**
     * Read Feature
     * Ficha completa de un feature: warnings, lessons learned y piezas ejemplo.
     * @param data The data for the request.
     * @param data.featureId
     * @returns FeatureDetail Successful Response
     * @throws ApiError
     */
    public static readFeature(data: FeaturesReadFeatureData): CancelablePromise<FeaturesReadFeatureResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/features/{feature_id}',
            path: {
                feature_id: data.featureId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Feature
     * Editar un feature. Cualquier usuario autenticado puede hacerlo: la base de
     * conocimiento es colaborativa.
     * @param data The data for the request.
     * @param data.featureId
     * @param data.requestBody
     * @returns FeaturePublic Successful Response
     * @throws ApiError
     */
    public static updateFeature(data: FeaturesUpdateFeatureData): CancelablePromise<FeaturesUpdateFeatureResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/features/{feature_id}',
            path: {
                feature_id: data.featureId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Feature
     * Borrar un feature con sus warnings, lessons learned y piezas ejemplo.
     * Solo el autor o un superusuario: es la unica accion irreversible.
     * @param data The data for the request.
     * @param data.featureId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteFeature(data: FeaturesDeleteFeatureData): CancelablePromise<FeaturesDeleteFeatureResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/features/{feature_id}',
            path: {
                feature_id: data.featureId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Feature Note
     * Anadir una advertencia (`kind=warning`) o leccion aprendida (`kind=lesson`).
     * @param data The data for the request.
     * @param data.featureId
     * @param data.requestBody
     * @returns FeatureNotePublic Successful Response
     * @throws ApiError
     */
    public static createFeatureNote(data: FeaturesCreateFeatureNoteData): CancelablePromise<FeaturesCreateFeatureNoteResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/features/{feature_id}/notes',
            path: {
                feature_id: data.featureId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Feature Note
     * Editar una advertencia o leccion aprendida.
     * @param data The data for the request.
     * @param data.noteId
     * @param data.requestBody
     * @returns FeatureNotePublic Successful Response
     * @throws ApiError
     */
    public static updateFeatureNote(data: FeaturesUpdateFeatureNoteData): CancelablePromise<FeaturesUpdateFeatureNoteResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/features/notes/{note_id}',
            path: {
                note_id: data.noteId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Feature Note
     * Borrar una advertencia o leccion aprendida.
     * @param data The data for the request.
     * @param data.noteId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteFeatureNote(data: FeaturesDeleteFeatureNoteData): CancelablePromise<FeaturesDeleteFeatureNoteResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/features/notes/{note_id}',
            path: {
                note_id: data.noteId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Feature Asset
     * Adjuntar una pieza ejemplo. El fichero se sube antes por `/files/` y aqui
     * se referencia con `file_id`.
     * @param data The data for the request.
     * @param data.featureId
     * @param data.requestBody
     * @returns FeatureAssetPublic Successful Response
     * @throws ApiError
     */
    public static createFeatureAsset(data: FeaturesCreateFeatureAssetData): CancelablePromise<FeaturesCreateFeatureAssetResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/features/{feature_id}/assets',
            path: {
                feature_id: data.featureId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Feature Asset
     * Editar una pieza ejemplo.
     * @param data The data for the request.
     * @param data.assetId
     * @param data.requestBody
     * @returns FeatureAssetPublic Successful Response
     * @throws ApiError
     */
    public static updateFeatureAsset(data: FeaturesUpdateFeatureAssetData): CancelablePromise<FeaturesUpdateFeatureAssetResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/features/assets/{asset_id}',
            path: {
                asset_id: data.assetId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Feature Asset
     * Quitar una pieza ejemplo del feature. El fichero subido no se borra.
     * @param data The data for the request.
     * @param data.assetId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteFeatureAsset(data: FeaturesDeleteFeatureAssetData): CancelablePromise<FeaturesDeleteFeatureAssetResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/features/assets/{asset_id}',
            path: {
                asset_id: data.assetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class FilesService {
    /**
     * Upload File
     * Subir un fichero (imagen de feature, CAD, plano PDF...).
     *
     * Los bytes van al disco (`settings.UPLOADS_DIR`) y la fila solo guarda los
     * metadatos. El id devuelto es el que se referencia desde el feature o desde
     * una de sus piezas ejemplo.
     * @param data The data for the request.
     * @param data.formData
     * @returns FilePublic Successful Response
     * @throws ApiError
     */
    public static uploadFile(data: FilesUploadFileData): CancelablePromise<FilesUploadFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read File
     * Servir un fichero por id.
     *
     * Sin autenticacion a proposito: el `<img src>` y los enlaces de descarga del
     * frontend no pueden mandar la cabecera Authorization. El id es un UUID v4,
     * que hace de secreto. Si algun dia hay ficheros confidenciales habra que
     * pasar a URLs firmadas.
     * @param data The data for the request.
     * @param data.fileId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static readFile(data: FilesReadFileData): CancelablePromise<FilesReadFileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/files/{file_id}',
            path: {
                file_id: data.fileId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete File
     * Borrar un fichero. Las referencias desde features y piezas ejemplo quedan a
     * NULL (ON DELETE SET NULL), no se borra la ficha.
     * @param data The data for the request.
     * @param data.fileId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteFile(data: FilesDeleteFileData): CancelablePromise<FilesDeleteFileResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/files/{file_id}',
            path: {
                file_id: data.fileId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}