// This file is auto-generated by @hey-api/openapi-ts

export type AssetKind = 'mold' | 'part' | 'scan' | 'drawing' | 'moldflow';

export type Body_files_upload_file = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CadCamera = {
    position: [
        number,
        number,
        number
    ];
    target: [
        number,
        number,
        number
    ];
    up: [
        number,
        number,
        number
    ];
};

export type CadFaceSelection = {
    mesh: number;
    face: number;
};

export type CharacteristicAssignment = {
    code: string;
    revision: string;
    role?: 'primary' | 'reference' | 'context';
};

export type role = 'primary' | 'reference' | 'context';

export type CharacteristicPublic = {
    id: string;
    part_id: string;
    code: string;
    revision: string;
    title: string;
    role?: (string | null);
};

export type DrawingPublic = {
    state: string;
    message?: (string | null);
    updated_at?: (string | null);
    payload?: {
        [key: string]: unknown;
    };
    reviews?: Array<LocationPublic>;
};

export type EvidenceDocument = {
    id: string;
    filename: string;
    content_type: string;
    size: number;
    created_at?: (string | null);
    source?: string;
    version?: (string | null);
    revision?: (string | null);
    relative_path?: (string | null);
};

export type FeatureAssetCreate = {
    kind: AssetKind;
    name: string;
    position?: number;
    part_id?: (string | null);
    file_id?: (string | null);
};

export type FeatureAssetOrder = {
    part_id?: (string | null);
    asset_ids: Array<(string)>;
};

export type FeatureAssetPublic = {
    kind: AssetKind;
    name: string;
    position?: number;
    id: string;
    feature_id: string;
    created_at?: (string | null);
    part?: (PartPublic | null);
    file?: (FilePublic | null);
};

export type FeatureAssetUpdate = {
    kind?: AssetKind;
    name?: string;
    position?: number;
    part_id?: (string | null);
    file_id?: (string | null);
};

export type FeatureCategory = 'hole' | 'rib' | 'thickness' | 'boss' | 'fillet' | 'draft' | 'other';

/**
 * An annotation tied to exact source bytes and a deterministic tessellation.
 */
export type FeatureCover3D = {
    asset_id: string;
    part_id: string;
    file_id: string;
    file_version?: (string | null);
    source_sha256: string;
    geometry_key: string;
    recipe: "occt-import-js@0.0.23/cover-v1";
    faces: Array<CadFaceSelection>;
    camera: CadCamera;
};

export type FeatureCreate = {
    name: string;
    description?: (string | null);
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    image_id?: (string | null);
};

export type FeatureDetail = {
    name: string;
    description?: (string | null);
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    id: string;
    created_at?: (string | null);
    owner_id?: (string | null);
    image?: (FilePublic | null);
    cover_3d?: (FeatureCover3D | null);
    part_order?: Array<(string)>;
    assets?: Array<FeatureAssetPublic>;
    parts?: Array<PartPublic>;
    notes?: Array<FeatureNotePublic>;
};

export type FeatureEvidencePublic = {
    characteristics: Array<CharacteristicPublic>;
    pending: Array<(string)>;
    cases: Array<(string)>;
};

export type FeatureFilterOption = {
    id: string;
    name: string;
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    part_ids?: Array<(string)>;
};

export type FeatureFilters = {
    categories: Array<FeatureCategory>;
    tags: Array<(string)>;
    parts: Array<PartPublic>;
    features: Array<FeatureFilterOption>;
};

export type FeatureNoteCreate = {
    kind: NoteKind;
    title: string;
    body?: (string | null);
    position?: number;
};

export type FeatureNoteOrder = {
    kind: NoteKind;
    note_ids: Array<(string)>;
};

export type FeatureNotePublic = {
    kind: NoteKind;
    title: string;
    body?: (string | null);
    position?: number;
    id: string;
    feature_id: string;
    created_at?: (string | null);
};

export type FeatureNoteUpdate = {
    kind?: NoteKind;
    title?: string;
    body?: (string | null);
    position?: number;
};

export type FeaturePartOrder = {
    part_ids: Array<(string)>;
};

export type FeaturePublic = {
    name: string;
    description?: (string | null);
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    id: string;
    created_at?: (string | null);
    owner_id?: (string | null);
    image?: (FilePublic | null);
    cover_3d?: (FeatureCover3D | null);
    part_order?: Array<(string)>;
    assets?: Array<FeatureAssetPublic>;
    parts?: Array<PartPublic>;
};

export type FeaturesPublic = {
    data: Array<FeaturePublic>;
    count: number;
};

export type FeatureUpdate = {
    name?: string;
    description?: (string | null);
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    image_id?: (string | null);
    cover_3d?: (FeatureCover3D | null);
};

export type FileAccessPublic = {
    url: string;
    expires_at: string;
};

export type FilePreviewPublic = {
    state: 'queued' | 'processing' | 'ready' | 'error';
    message?: (string | null);
    url?: (string | null);
};

export type state = 'queued' | 'processing' | 'ready' | 'error';

export type FilePublic = {
    id: string;
    filename: string;
    content_type: string;
    size: number;
    created_at?: (string | null);
    source?: string;
    version?: (string | null);
    revision?: (string | null);
};

export type FileStatus = {
    state: 'available' | 'missing' | 'changed' | 'unavailable';
    message: string;
    path?: (string | null);
};

export type state2 = 'available' | 'missing' | 'changed' | 'unavailable';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: string;
    description?: (string | null);
};

export type JobPublic = {
    state: string;
    message?: (string | null);
    updated_at?: (string | null);
    payload?: {
        [key: string]: unknown;
    };
};

export type LocalFileReference = {
    path: string;
    revision?: (string | null);
};

export type LocationPublic = {
    id: string;
    candidate_id: string;
    label: string;
    page: number;
    box: Array<(number)>;
    reviewed_by: (string | null);
    reviewed_at: string;
};

export type LocationReview = {
    sha256: string;
    candidate_id: string;
    label: string;
};

export type Message = {
    message: string;
};

export type MetrologyCatalog = {
    data: Array<MetrologyPart>;
    count: number;
    features: Array<MetrologyFeature>;
};

export type MetrologyFeature = {
    id: string;
    name: string;
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    characteristics?: Array<CharacteristicPublic>;
};

export type MetrologyFeatureChoice = {
    id: string;
    name: string;
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    part_ids?: Array<(string)>;
};

export type MetrologyFilters = {
    parts: Array<PartPublic>;
    features: Array<MetrologyFeatureChoice>;
};

export type MetrologyPart = {
    part: PartPublic;
    features: Array<MetrologyFeature>;
    matched_feature_ids?: Array<(string)>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NoteKind = 'warning' | 'lesson';

export type PartCatalogPublic = {
    code: string;
    name?: (string | null);
    folder_path?: (string | null);
    id: string;
    created_at?: (string | null);
    feature_count: number;
};

export type PartCreate = {
    code: string;
    name?: (string | null);
    folder_path?: (string | null);
};

export type PartEvidencePublic = {
    part: PartPublic;
    documents: Array<EvidenceDocument>;
    characteristics: Array<CharacteristicPublic>;
    features?: Array<MetrologyFeature>;
    study: JobPublic;
    import_available: boolean;
};

export type PartFromFolder = {
    folder_path: string;
};

export type PartPublic = {
    code: string;
    name?: (string | null);
    folder_path?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type PartsPublic = {
    data: Array<PartCatalogPublic>;
    count: number;
};

export type PartUpdate = {
    code?: string;
    name?: (string | null);
    folder_path?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RelinkFileReference = {
    path: string;
    revision?: (string | null);
    expected_version: string;
};

export type SourceEntry = {
    name: string;
    path: string;
    directory: boolean;
    size?: (number | null);
};

export type SourceListing = {
    configured: boolean;
    name: string;
    path: string;
    entries: Array<SourceEntry>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: string;
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type EvidenceReadMetrologyFiltersResponse = (MetrologyFilters);

export type EvidenceReadMetrologyData = {
    featureId?: (string | null);
    limit?: number;
    q?: string;
    skip?: number;
};

export type EvidenceReadMetrologyResponse = (MetrologyCatalog);

export type EvidenceReadPartEvidenceData = {
    partId: string;
};

export type EvidenceReadPartEvidenceResponse = (PartEvidencePublic);

export type EvidenceImportPartEvidenceData = {
    partId: string;
};

export type EvidenceImportPartEvidenceResponse = (JobPublic);

export type EvidenceReadFeatureEvidenceData = {
    featureId: string;
    partId: string;
};

export type EvidenceReadFeatureEvidenceResponse = (FeatureEvidencePublic);

export type EvidenceAssignCharacteristicData = {
    featureId: string;
    partId: string;
    requestBody: CharacteristicAssignment;
};

export type EvidenceAssignCharacteristicResponse = (CharacteristicPublic);

export type EvidenceUnassignCharacteristicData = {
    characteristicId: string;
    featureId: string;
};

export type EvidenceUnassignCharacteristicResponse = (Message);

export type EvidenceReadDrawingIndexData = {
    fileId: string;
};

export type EvidenceReadDrawingIndexResponse = (DrawingPublic);

export type EvidenceIndexDrawingData = {
    fileId: string;
};

export type EvidenceIndexDrawingResponse = (JobPublic);

export type EvidenceReviewDrawingLocationData = {
    fileId: string;
    requestBody: LocationReview;
};

export type EvidenceReviewDrawingLocationResponse = (LocationPublic);

export type FeaturesReadFeaturesData = {
    category?: (FeatureCategory | null);
    featureId?: (string | null);
    limit?: number;
    partId?: (string | null);
    q?: (string | null);
    skip?: number;
    tag?: (string | null);
};

export type FeaturesReadFeaturesResponse = (FeaturesPublic);

export type FeaturesCreateFeatureData = {
    requestBody: FeatureCreate;
};

export type FeaturesCreateFeatureResponse = (FeaturePublic);

export type FeaturesReadFeatureFiltersResponse = (FeatureFilters);

export type FeaturesReadFeatureData = {
    featureId: string;
};

export type FeaturesReadFeatureResponse = (FeatureDetail);

export type FeaturesUpdateFeatureData = {
    featureId: string;
    requestBody: FeatureUpdate;
};

export type FeaturesUpdateFeatureResponse = (FeaturePublic);

export type FeaturesDeleteFeatureData = {
    featureId: string;
};

export type FeaturesDeleteFeatureResponse = (Message);

export type FeaturesReorderFeatureNotesData = {
    featureId: string;
    requestBody: FeatureNoteOrder;
};

export type FeaturesReorderFeatureNotesResponse = (Message);

export type FeaturesReorderFeatureAssetsData = {
    featureId: string;
    requestBody: FeatureAssetOrder;
};

export type FeaturesReorderFeatureAssetsResponse = (Message);

export type FeaturesCreateFeatureNoteData = {
    featureId: string;
    requestBody: FeatureNoteCreate;
};

export type FeaturesCreateFeatureNoteResponse = (FeatureNotePublic);

export type FeaturesUpdateFeatureNoteData = {
    noteId: string;
    requestBody: FeatureNoteUpdate;
};

export type FeaturesUpdateFeatureNoteResponse = (FeatureNotePublic);

export type FeaturesDeleteFeatureNoteData = {
    noteId: string;
};

export type FeaturesDeleteFeatureNoteResponse = (Message);

export type FeaturesReorderFeaturePartsData = {
    featureId: string;
    requestBody: FeaturePartOrder;
};

export type FeaturesReorderFeaturePartsResponse = (FeatureDetail);

export type FeaturesLinkFeaturePartData = {
    featureId: string;
    partId: string;
};

export type FeaturesLinkFeaturePartResponse = (FeatureDetail);

export type FeaturesUnlinkFeaturePartData = {
    featureId: string;
    partId: string;
};

export type FeaturesUnlinkFeaturePartResponse = (Message);

export type FeaturesCreateFeatureAssetData = {
    featureId: string;
    requestBody: FeatureAssetCreate;
};

export type FeaturesCreateFeatureAssetResponse = (FeatureAssetPublic);

export type FeaturesUpdateFeatureAssetData = {
    assetId: string;
    requestBody: FeatureAssetUpdate;
};

export type FeaturesUpdateFeatureAssetResponse = (FeatureAssetPublic);

export type FeaturesDeleteFeatureAssetData = {
    assetId: string;
};

export type FeaturesDeleteFeatureAssetResponse = (Message);

export type FilesListSourceData = {
    directoriesOnly?: boolean;
    limit?: number;
    path?: string;
    skip?: number;
};

export type FilesListSourceResponse = (SourceListing);

export type FilesReferenceFileData = {
    requestBody: LocalFileReference;
};

export type FilesReferenceFileResponse = (FilePublic);

export type FilesRelinkFileData = {
    fileId: string;
    requestBody: RelinkFileReference;
};

export type FilesRelinkFileResponse = (FilePublic);

export type FilesFileStatusData = {
    fileId: string;
};

export type FilesFileStatusResponse = (FileStatus);

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
};

export type FilesUploadFileResponse = (FilePublic);

export type FilesCreateFileAccessUrlData = {
    download?: boolean;
    fileId: string;
};

export type FilesCreateFileAccessUrlResponse = (FileAccessPublic);

export type FilesPreparePreviewData = {
    fileId: string;
    retry?: boolean;
};

export type FilesPreparePreviewResponse = (FilePreviewPublic);

export type FilesReadPreviewData = {
    fileId: string;
    token?: (string | null);
};

export type FilesReadPreviewResponse = (unknown);

export type FilesReadFileData = {
    download?: boolean;
    fileId: string;
    token?: (string | null);
};

export type FilesReadFileResponse = (unknown);

export type FilesDeleteFileData = {
    fileId: string;
};

export type FilesDeleteFileResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PartsReadPartsData = {
    limit?: number;
    skip?: number;
};

export type PartsReadPartsResponse = (PartsPublic);

export type PartsCreatePartData = {
    requestBody: PartCreate;
};

export type PartsCreatePartResponse = (PartPublic);

export type PartsCreatePartFromFolderData = {
    requestBody: PartFromFolder;
};

export type PartsCreatePartFromFolderResponse = (PartPublic);

export type PartsUpdatePartData = {
    partId: string;
    requestBody: PartUpdate;
};

export type PartsUpdatePartResponse = (PartPublic);

export type PartsDeletePartData = {
    partId: string;
};

export type PartsDeletePartResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);