// This file is auto-generated by @hey-api/openapi-ts

export type AssetKind = 'mold' | 'part' | 'scan' | 'drawing' | 'moldflow';

export type Body_files_upload_file = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FeatureAssetCreate = {
    kind: AssetKind;
    name: string;
    position?: number;
    part_id?: (string | null);
    file_id?: (string | null);
};

export type FeatureAssetPublic = {
    kind: AssetKind;
    name: string;
    position?: number;
    id: string;
    feature_id: string;
    created_at?: (string | null);
    part?: (PartPublic | null);
    file?: (FilePublic | null);
};

export type FeatureAssetUpdate = {
    kind?: (AssetKind | null);
    name?: (string | null);
    position?: (number | null);
    part_id?: (string | null);
    file_id?: (string | null);
};

export type FeatureCategory = 'hole' | 'rib' | 'thickness' | 'boss' | 'fillet' | 'draft' | 'other';

export type FeatureCreate = {
    name: string;
    description?: (string | null);
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    image_id?: (string | null);
};

export type FeatureDetail = {
    name: string;
    description?: (string | null);
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    id: string;
    created_at?: (string | null);
    owner_id?: (string | null);
    image?: (FilePublic | null);
    assets?: Array<FeatureAssetPublic>;
    parts?: Array<PartPublic>;
    notes?: Array<FeatureNotePublic>;
};

export type FeatureFilters = {
    categories: Array<FeatureCategory>;
    tags: Array<(string)>;
    parts: Array<PartPublic>;
};

export type FeatureNoteCreate = {
    kind: NoteKind;
    title: string;
    body?: (string | null);
    position?: number;
};

export type FeatureNotePublic = {
    kind: NoteKind;
    title: string;
    body?: (string | null);
    position?: number;
    id: string;
    feature_id: string;
    created_at?: (string | null);
};

export type FeatureNoteUpdate = {
    kind?: (NoteKind | null);
    title?: (string | null);
    body?: (string | null);
    position?: (number | null);
};

export type FeaturePublic = {
    name: string;
    description?: (string | null);
    category?: (FeatureCategory | null);
    tags?: Array<(string)>;
    id: string;
    created_at?: (string | null);
    owner_id?: (string | null);
    image?: (FilePublic | null);
    assets?: Array<FeatureAssetPublic>;
    parts?: Array<PartPublic>;
};

export type FeaturesPublic = {
    data: Array<FeaturePublic>;
    count: number;
};

export type FeatureUpdate = {
    name?: (string | null);
    description?: (string | null);
    category?: (FeatureCategory | null);
    tags?: (Array<(string)> | null);
    image_id?: (string | null);
};

export type FilePublic = {
    id: string;
    filename: string;
    content_type: string;
    size: number;
    created_at?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NoteKind = 'warning' | 'lesson';

export type PartCreate = {
    code: string;
    name?: (string | null);
};

export type PartPublic = {
    code: string;
    name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type PartsPublic = {
    data: Array<PartPublic>;
    count: number;
};

export type PartUpdate = {
    code?: (string | null);
    name?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type FeaturesReadFeaturesData = {
    category?: (FeatureCategory | null);
    limit?: number;
    partId?: (string | null);
    q?: (string | null);
    skip?: number;
    tag?: (string | null);
};

export type FeaturesReadFeaturesResponse = (FeaturesPublic);

export type FeaturesCreateFeatureData = {
    requestBody: FeatureCreate;
};

export type FeaturesCreateFeatureResponse = (FeaturePublic);

export type FeaturesReadFeatureFiltersResponse = (FeatureFilters);

export type FeaturesReadFeatureData = {
    featureId: string;
};

export type FeaturesReadFeatureResponse = (FeatureDetail);

export type FeaturesUpdateFeatureData = {
    featureId: string;
    requestBody: FeatureUpdate;
};

export type FeaturesUpdateFeatureResponse = (FeaturePublic);

export type FeaturesDeleteFeatureData = {
    featureId: string;
};

export type FeaturesDeleteFeatureResponse = (Message);

export type FeaturesCreateFeatureNoteData = {
    featureId: string;
    requestBody: FeatureNoteCreate;
};

export type FeaturesCreateFeatureNoteResponse = (FeatureNotePublic);

export type FeaturesUpdateFeatureNoteData = {
    noteId: string;
    requestBody: FeatureNoteUpdate;
};

export type FeaturesUpdateFeatureNoteResponse = (FeatureNotePublic);

export type FeaturesDeleteFeatureNoteData = {
    noteId: string;
};

export type FeaturesDeleteFeatureNoteResponse = (Message);

export type FeaturesLinkFeaturePartData = {
    featureId: string;
    partId: string;
};

export type FeaturesLinkFeaturePartResponse = (FeatureDetail);

export type FeaturesUnlinkFeaturePartData = {
    featureId: string;
    partId: string;
};

export type FeaturesUnlinkFeaturePartResponse = (Message);

export type FeaturesCreateFeatureAssetData = {
    featureId: string;
    requestBody: FeatureAssetCreate;
};

export type FeaturesCreateFeatureAssetResponse = (FeatureAssetPublic);

export type FeaturesUpdateFeatureAssetData = {
    assetId: string;
    requestBody: FeatureAssetUpdate;
};

export type FeaturesUpdateFeatureAssetResponse = (FeatureAssetPublic);

export type FeaturesDeleteFeatureAssetData = {
    assetId: string;
};

export type FeaturesDeleteFeatureAssetResponse = (Message);

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
};

export type FilesUploadFileResponse = (FilePublic);

export type FilesReadFileData = {
    fileId: string;
};

export type FilesReadFileResponse = (unknown);

export type FilesDeleteFileData = {
    fileId: string;
};

export type FilesDeleteFileResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PartsReadPartsData = {
    limit?: number;
    skip?: number;
};

export type PartsReadPartsResponse = (PartsPublic);

export type PartsCreatePartData = {
    requestBody: PartCreate;
};

export type PartsCreatePartResponse = (PartPublic);

export type PartsUpdatePartData = {
    partId: string;
    requestBody: PartUpdate;
};

export type PartsUpdatePartResponse = (PartPublic);

export type PartsDeletePartData = {
    partId: string;
};

export type PartsDeletePartResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);