export type { ChatRequest } from "@/client"

export type Source = { label: string; url: string }
export type ChatTurn = {
  id: string
  question: string
  answer: string
  sources: Source[]
  complete: boolean
  error?: string
  truncated?: boolean
}
export type StreamEvent =
  | { type: "status" | "delta" | "error"; text: string }
  | { type: "sources"; sources: Source[] }
  | { type: "done"; truncated?: boolean }

// Only links generated by the backend's allowlisted readers are navigable.
export function isSource(value: unknown): value is Source {
  if (!value || typeof value !== "object") return false
  const source = value as Source
  return (
    typeof source.label === "string" &&
    typeof source.url === "string" &&
    /^\/(parts|features)\/[0-9a-f-]{36}(\?[^#]*)?$/i.test(source.url)
  )
}
