/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutFeaturesRouteImport } from './routes/_layout/features'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutFeaturesNuevoRouteImport } from './routes/_layout/features_.nuevo'
import { Route as LayoutFeaturesFeatureIdRouteImport } from './routes/_layout/features_.$featureId'
import { Route as LayoutFeaturesFeatureIdFicheroAssetIdRouteImport } from './routes/_layout/features_.$featureId_.fichero.$assetId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeaturesRoute = LayoutFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeaturesNuevoRoute = LayoutFeaturesNuevoRouteImport.update({
  id: '/features_/nuevo',
  path: '/features/nuevo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeaturesFeatureIdRoute = LayoutFeaturesFeatureIdRouteImport.update({
  id: '/features_/$featureId',
  path: '/features/$featureId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeaturesFeatureIdFicheroAssetIdRoute =
  LayoutFeaturesFeatureIdFicheroAssetIdRouteImport.update({
    id: '/features_/$featureId_/fichero/$assetId',
    path: '/features/$featureId/fichero/$assetId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/features': typeof LayoutFeaturesRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/features/$featureId': typeof LayoutFeaturesFeatureIdRoute
  '/features/nuevo': typeof LayoutFeaturesNuevoRoute
  '/features/$featureId/fichero/$assetId': typeof LayoutFeaturesFeatureIdFicheroAssetIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/features': typeof LayoutFeaturesRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/features/$featureId': typeof LayoutFeaturesFeatureIdRoute
  '/features/nuevo': typeof LayoutFeaturesNuevoRoute
  '/features/$featureId/fichero/$assetId': typeof LayoutFeaturesFeatureIdFicheroAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/features': typeof LayoutFeaturesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/features_/$featureId': typeof LayoutFeaturesFeatureIdRoute
  '/_layout/features_/nuevo': typeof LayoutFeaturesNuevoRoute
  '/_layout/features_/$featureId_/fichero/$assetId': typeof LayoutFeaturesFeatureIdFicheroAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/features'
    | '/items'
    | '/settings'
    | '/features/$featureId'
    | '/features/nuevo'
    | '/features/$featureId/fichero/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/features'
    | '/items'
    | '/settings'
    | '/'
    | '/features/$featureId'
    | '/features/nuevo'
    | '/features/$featureId/fichero/$assetId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/features'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/features_/$featureId'
    | '/_layout/features_/nuevo'
    | '/_layout/features_/$featureId_/fichero/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/features': {
      id: '/_layout/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof LayoutFeaturesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/features_/nuevo': {
      id: '/_layout/features_/nuevo'
      path: '/features/nuevo'
      fullPath: '/features/nuevo'
      preLoaderRoute: typeof LayoutFeaturesNuevoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/features_/$featureId': {
      id: '/_layout/features_/$featureId'
      path: '/features/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof LayoutFeaturesFeatureIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/features_/$featureId_/fichero/$assetId': {
      id: '/_layout/features_/$featureId_/fichero/$assetId'
      path: '/features/$featureId/fichero/$assetId'
      fullPath: '/features/$featureId/fichero/$assetId'
      preLoaderRoute: typeof LayoutFeaturesFeatureIdFicheroAssetIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutFeaturesRoute: typeof LayoutFeaturesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFeaturesFeatureIdRoute: typeof LayoutFeaturesFeatureIdRoute
  LayoutFeaturesNuevoRoute: typeof LayoutFeaturesNuevoRoute
  LayoutFeaturesFeatureIdFicheroAssetIdRoute: typeof LayoutFeaturesFeatureIdFicheroAssetIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutFeaturesRoute: LayoutFeaturesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFeaturesFeatureIdRoute: LayoutFeaturesFeatureIdRoute,
  LayoutFeaturesNuevoRoute: LayoutFeaturesNuevoRoute,
  LayoutFeaturesFeatureIdFicheroAssetIdRoute:
    LayoutFeaturesFeatureIdFicheroAssetIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
